name = "modpack"
author = "Paul Wood"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b79885b772f496887e3c8b1f4d29320b8fe38a2c18384c962322e9805f7e61e5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
