name = "modpack"
author = "Paul Wood"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "507c9a8acd35062e8dac0a5c8894b0dd355949f809319cbc87d33a079c400a7a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
