name = "modpack"
author = "Paul Wood"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85cb04a363f829d45ec72a4a27f069758ce8c05eccb12c827aebe7ccdf27dc16"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
