name = "modpack"
author = "Paul Wood"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cf69bcf5ed4d5b0159ba3420cd158af55ffa8b1ad8d4299b7d04187f1c00398"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
